language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

sudo: false

env:
  global:
    - CODECOV_TOKEN="8e909e77-4042-40d9-91d8-4276a3c5aa02"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -prostokota@list.ru
    on_success: never # default: change
    on_failure: always # default: always